const COURSES = [
  {
    title: "React The Ultimate Google Ads Training Course Beginners",
    category: "Marketing",
    price: "$100",
    avatar: "../img/1.png",
    author: "| by Jerome Bell",
  },
  {
    title: " Product Management Fundamentals Basics",
    category: "Management",
    price: "$480",
    avatar: "../img/2.png",
    author: "| by Marvin McKinney",
  },
  {
    title: "HR  Management and Analytics 101",
    category: "HR & Recruiting",
    price: "$200",
    avatar: "../img/3.png",
    author: "| by Leslie Alexander Li",
  },
  {
    title: "React Brand Management & PR Communications Beginners",
    category: "Marketing",
    price: "$530",
    avatar: "../img/4.png",
    author: "| by Kristin Watson",
  },
  {
    title: "Graphic Design Basic",
    category: "Design",
    price: "$500",
    avatar: "../img/5.png",
    author: "| by Jerome Bell",
  },
  {
    title: "Business Development Management ",
    category: "Management",
    price: "$400",
    avatar: "../img/6.png",
    author: "| by Guy Hawkins",
  },
  {
    title: "Highload Software Architecture",
    category: "Development",
    price: "$600",
    avatar: "../img/7.png",
    author: "| by Dianne Russell",
  },
  {
    title: "Human Resources – Selection and Recruitment",
    category: "HR & Recruiting",
    price: "$150",
    avatar: "../img/8.png",
    author: "| by Kathryn Murphy",
  },
  {
    title: "Marketing User Experience. Human-centered Design",
    category: "Design",
    price: "$240",
    avatar: "../img/9.png",
    author: "| by Cody Fisher",
  },
];
